### ISSUE TITLE
TID length

### ISSUE THREAD

**Issue by billvoss** [sparkfun/Simultaneous_RFID_Tag_Reader#5] opened 2018-04-16 03:23 UTC
Hi,

I'm having an issue where the 12th byte of the tag TID randomly changes on each read. 

I noticed that the code says that TIDs are 20 bytes (line 10, Example9_Read_TID.ino), but the product page (and ThingMagic) say that the TIDs are 64 bits (https://www.sparkfun.com/products/14151).

Do you know what's going on here?

Thanks

**Comment by nseidle** [comment] 2018-04-18 19:00
I've been digging into this. I think the short answer is that most tag TIDs are 64 bit or 8 byte. The long answer is that it can be variable.

Here's the Gen2 Spec: https://www.gs1.org/sites/default/files/docs/epc/GS1_EPC_TDS_i1_10.pdf

See section 16.2.2 XTID Serialization. There's room for a variable length TID.

I'm going to keep testing and looking for a tag that has more than 8 bytes. In the mean time, you may want to adjust your code so it only looks at the first 8 bytes returns from the TID function call.

**Comment by nseidle** [comment] 2018-04-18 19:13
Closing this issue out. It's a duplicate of this: https://github.com/sparkfun/SparkFun_Simultaneous_RFID_Tag_Reader_Library/issues/8

**Closed by nseidle** 2018-04-18 19:13 UTC
